#!/bin/bash
####
# Simple script to download epg data in xmltv format from website https://www.xmltv.net/
#
# switches
#    -s video source id
#    -r region (e.g. Sydney, Melbourne, etc)
#    -f flag to tell mythfilldatabase to update new channels and icons (OPTIONAL - if not specified, runs mythfilldatabase with the --update flag)
# usage
#    tv_grab_au_file -s 1 -r Sydney -f
#
#  VERSION HISTORY
#  01/07/2021 - Initial version
#  20/09/2022 - Change channel 92 to 95 as yourtv is missing EPG for that channel
#
####

TARGET_XML=/tmp/epg.xml
UPDATE="--update"

while getopts s:r: flag
do
    case "${flag}" in
        s) SOURCEID=${OPTARG};;
        r) REGION=${OPTARG};;
        f) UPDATE="";;
    esac
done

#sanity check for mandatory switches
[ -z "$SOURCEID" ] && echo "Source id (-s) not specified" && exit 1
[ -z "$REGION" ] && echo "Region (-r) not specified" && exit 1


#remove any old file
rm -f $TARGET_XML

#grab xmltv file from website
wget http://xmltv.net/xml_files/$REGION.xml -O $TARGET_XML

#clean up channel names to match OTA ones (region dependent)
if [ "$REGION" == "Sydney" ] 
then
    echo "Cleaning up channel names in downloaded guide data for Sydney"
    #remove trailing NSW
    sed -i 's/ NSW<\/display-name>/<\/display-name>/g' $TARGET_XML
    #remove trailing Sydney
    sed -i 's/ Sydney<\/display-name>/<\/display-name>/g' $TARGET_XML
    #add trailing Sydney for 7 channels
    sed -i 's/>7\(.*\)<\/display-name>/>7\1 Sydney<\/display-name>/g' $TARGET_XML

    #latest EPG is missing content for 9GEM HD (aka channel 95). Since it is a duplicate of channel 92 (the SDTV version), let's just swap channel 92 for 95 and the quality attribute.
    #need to massage the newlines in the file so sed can match across child elements in the programme tag
    cat $TARGET_XML | tr -d '\n' | sed 's/<\/programme>\r/<\/programme>\n/g' | sed 's/ channel="92\(.*\)SDTV/ channel="95\1HDTV/g' | tr '\r' '\n' > $TARGET_XML
fi

#populate mythtv if download is successful
[ -s $TARGET_XML ] && mythfilldatabase --file --sourceid $SOURCEID --xmlfile $TARGET_XML $UPDATE


exit 0
